version: '3.7'

services:

  seq:
   image: datalust/seq
   container_name: seq
   environment:
    - ACCEPT_EULA=Y
   ports:
    - "80:80"
    - "5341:5341"
   volumes:
    - seq-data:/data

volumes:
  seq-data: